AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "spec/fixtures/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 60

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - "lib/jekyll-ai-visible-content.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Gemspec/DevelopmentDependencies:
  Enabled: false
